/**
 * Tally XML export for AI Accountant (Module F).
 *
 * We don't have live access to a dealer's Tally XML/ODBC server from here, so instead
 * of pushing vouchers over HTTP (what the "Tally Connector" desktop agent would do in
 * production), this generates the same Tally-importable XML the dealer or their
 * accountant can import manually via: Gateway of Tally > Import Data > Vouchers > XML.
 *
 * Docs: https://help.tallysolutions.com/tally-prime/xml-api/
 */

interface DocumentLike {
  id: string;
  category: string;
  filename: string | null;
  ocr_data: any;
  created_at?: Date;
}

/** Map our bill categories to Tally voucher types */
const VOUCHER_TYPE: Record<string, string> = {
  tractor_purchase: 'Purchase',
  spare_purchase:   'Purchase',
  tractor_sales:    'Sales',
  spare_sales:      'Sales',
  cash_voucher:     'Payment',
  other:            'Journal',
};

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function voucherXml(doc: DocumentLike, dealerName: string): string {
  const ocr = doc.ocr_data ?? {};
  const voucherType = VOUCHER_TYPE[doc.category] ?? 'Journal';
  const date = (ocr.date ? String(ocr.date).replace(/-/g, '') : new Date(doc.created_at ?? Date.now()).toISOString().slice(0, 10).replace(/-/g, ''));
  const amount = Number(ocr.amount ?? 0);
  const vendor = escapeXml(ocr.vendor ?? doc.filename ?? 'Unknown Party');
  const narration = escapeXml(ocr.raw_text ?? `${doc.category} — ${doc.filename ?? doc.id}`);
  const invoiceNo = escapeXml(ocr.invoice_number ?? doc.id.slice(0, 10));

  return `
    <TALLYMESSAGE xmlns:UDF="TallyUDF">
      <VOUCHER VCHTYPE="${voucherType}" ACTION="Create">
        <DATE>${date}</DATE>
        <NARRATION>${narration}</NARRATION>
        <VOUCHERTYPENAME>${voucherType}</VOUCHERTYPENAME>
        <VOUCHERNUMBER>${invoiceNo}</VOUCHERNUMBER>
        <PARTYNAME>${vendor}</PARTYNAME>
        <ALLLEDGERENTRIES.LIST>
          <LEDGERNAME>${vendor}</LEDGERNAME>
          <ISDEEMEDPOSITIVE>${voucherType === 'Sales' ? 'No' : 'Yes'}</ISDEEMEDPOSITIVE>
          <AMOUNT>${voucherType === 'Sales' ? amount : -amount}</AMOUNT>
        </ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST>
          <LEDGERNAME>${voucherType}</LEDGERNAME>
          <ISDEEMEDPOSITIVE>${voucherType === 'Sales' ? 'No' : 'Yes'}</ISDEEMEDPOSITIVE>
          <AMOUNT>${voucherType === 'Sales' ? -amount : amount}</AMOUNT>
        </ALLLEDGERENTRIES.LIST>
      </VOUCHER>
    </TALLYMESSAGE>`;
}

export function buildTallyXml(dealerName: string, periodMonth: string, documents: DocumentLike[]): string {
  const vouchers = documents.map(d => voucherXml(d, dealerName)).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<ENVELOPE>
  <HEADER>
    <TALLYREQUEST>Import Data</TALLYREQUEST>
  </HEADER>
  <BODY>
    <IMPORTDATA>
      <REQUESTDESC>
        <REPORTNAME>Vouchers</REPORTNAME>
        <STATICVARIABLES>
          <SVCURRENTCOMPANY>${escapeXml(dealerName)}</SVCURRENTCOMPANY>
        </STATICVARIABLES>
      </REQUESTDESC>
      <REQUESTDATA>
        <!-- Generated by AgroDesk AI Accountant for ${escapeXml(periodMonth)} — ${documents.length} voucher(s) -->${vouchers}
      </REQUESTDATA>
    </IMPORTDATA>
  </BODY>
</ENVELOPE>`;
}
